import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

export type Lang = 'en' | 'de';

interface LanguageContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Nav
    'nav.home':       'Home',
    'nav.solutions':  'Solutions',
    'nav.liveDemo':   'Demo',
    'nav.pricing':    'Pricing',
    'nav.faq':        'FAQ',
    'nav.contact':    'Contact',
    'nav.cta':        'Book your free audit',

    // Hero
    'hero.headline':       'Your offer is right. The path to booking it is not.',
    'hero.subline':        'Most businesses lose bookings quietly. Always at the same places.',
    'hero.cta.primary':    'Book your free audit',
    'hero.cta.secondary':  'See the demo',
    'hero.badge.1':        'Zürich-based',
    'hero.badge.2':        'Mobile-first',
    'hero.badge.3':        'Website · Google · Bookings',
    'hero.trust':          'Based in Zürich. Personally reviewed. Clear next steps within 24 hours.',
    'hero.callout.1':      '',
    'hero.callout.2':      'Most lost bookings happen before anyone calls.',
    'hero.callout.3':      '',

    // Sticky CTA
    'sticky.cta': 'Book your free audit',

    // Before/After section
    'before.label':       'The difference',
    'before.headline.1':  'Customers drop off.',
    'before.headline.2':  'Or they know exactly what to do next.',
    'before.col.before':  'Before',
    'before.col.after':   'After',
    'before.item.1':      'No clickable phone number on mobile',
    'before.item.2':      'Google listing incomplete or missing hours',
    'before.item.3':      'Site loads too slowly. Visitor leaves in 3 seconds.',
    'before.item.4':      'Missed call with no automatic follow-up',
    'before.item.5':      'Booking only via Instagram DM or Treatwell',
    'after.item.1':       'Phone number taps directly to call',
    'after.item.2':       'Google profile complete, reviewed, and indexed',
    'after.item.3':       'Site loads in under 2 seconds on mobile data',
    'after.item.4':       'Missed call triggers an automatic callback message',
    'after.item.5':       'Client can book in under 10 seconds from search',

    // Problem section
    'problem.eyebrow':         'The real problem',
    'problem.headline.1':      'The problem is not your marketing.',
    'problem.headline.2':      'It is your booking path.',
    'problem.body':            'Most bookings are lost before anyone calls.',
    'problem.0.title':         'No clear next step',
    'problem.0.desc':          "Visitors like what they see but don't know what to do next. No booking link, no clear contact path.",
    'problem.1.title':         'Missed calls disappear',
    'problem.1.desc':          "You're in a session. The phone rings, you miss it. Nobody follows up. The customer books elsewhere.",
    'problem.2.title':         'Mobile page creates friction',
    'problem.2.desc':          'Most customers check you on their phone. If the page is unclear or slow, they leave before contacting you.',
    'problem.3.title':         'Trust appears too late',
    'problem.3.desc':          "Reviews, services, and pricing need to show up early. If they're buried or missing, customers hesitate and leave.",
    'problem.niches.label':    "Who it's for",
    'problem.niches.headline': 'Works for any local business where bookings matter',
    'problem.niche.0.title':   'Beauty and Wellness',
    'problem.niche.0.desc':    'Massage studios, salons, nail studios, kosmetik',
    'problem.niche.1.title':   'Health and Medical',
    'problem.niche.1.desc':    'Physiotherapists, podologists, medical cosmetics',
    'problem.niche.2.title':   'Local Tradespeople',
    'problem.niche.2.desc':    'Plumbers, caterers, anyone who lives by the phone',
    'problem.leak.label':      'Leak',

    // Demo section
    'demo.eyebrow':   'LIVE DEMO',
    'demo.headline':  'See what a booking-ready website looks like',
    'demo.subline':   'A real example showing how services, trust, mobile booking, and clear user flow work together.',
    'demo.bullet.1':  'Clear services and pricing',
    'demo.bullet.2':  'Booking CTA visible early',
    'demo.bullet.3':  'Mobile-first for local customers',
    'demo.note':      'Demo uses Maison Lumière as an example business.',
    'demo.caption':   'Demo example: Maison Lumière Beauty Studio, Zürich. Built to show how LumaFlow turns a local business into a booking-ready online presence.',
    'demo.cta':       'See the demo',

    // Solution section
    'solution.eyebrow':      'WHAT I FIX',
    'solution.headline':     'I turn a leaky booking path into a clear customer journey.',
    'solution.subline':      'LumaFlow connects the pieces most local businesses leave scattered: website, Google profile, booking flow, phone contact, and follow-up.',
    'solution.card1.title':  'Clear mobile booking path',
    'solution.card1.copy':   'Customers see your services, trust your business, and know exactly how to book from their phone.',
    'solution.card2.title':  'Google-ready local presence',
    'solution.card2.copy':   'Your website and Google profile work together so customers can find you, understand you, and contact you faster.',
    'solution.card3.title':  'Missed-call recovery',
    'solution.card3.copy':   'If you miss a call, the customer still gets a fast follow-up instead of disappearing to another provider.',
    'solution.cta':          'Book your free audit',

    // Pricing section
    'pricing.eyebrow':              'Packages',
    'pricing.section.headline':     'Start where it makes sense for your business',
    'pricing.section.subline':      'Every project starts with a free audit so you know exactly what makes sense before you commit.',
    'pricing.badge':                'Most popular',
    'pricing.from':                 'from',
    'pricing.cta':                  'Book your free audit',
    'pricing.tier.localPresence':   'Local Presence',
    'pricing.tier.bookingWebsite':  'Booking Website',
    'pricing.tier.fullRecovery':    'Full Booking Recovery System',
    'pricing.tagline.localPresence':  'For businesses that need a clean, findable presence.',
    'pricing.tagline.bookingWebsite': 'For businesses that want more visitors to turn into bookings.',
    'pricing.tagline.fullRecovery':   'For businesses that need website, booking setup, and follow-up flow.',
    'pricing.feature.lp.1':   'Clients can find you on Google',
    'pricing.feature.lp.2':   'Your phone number works on mobile',
    'pricing.feature.lp.3':   'Google Business Profile complete and indexed',
    'pricing.feature.lp.4':   'Delivered in 1 week',
    'pricing.feature.bw.1':   'Clients can book in under 10 seconds from search',
    'pricing.feature.bw.2':   'Clickable phone, booking form, Google Maps',
    'pricing.feature.bw.3':   'FAQ section that reduces pre-booking calls',
    'pricing.feature.bw.4':   'Local SEO structure built in',
    'pricing.feature.bw.5':   'Delivered in 1 week',
    'pricing.feature.br.1':   'Everything in Booking Website',
    'pricing.feature.br.2':   'Automated missed-call follow-up',
    'pricing.feature.br.3':   'Google Business Profile optimised',
    'pricing.feature.br.4':   'Review request workflow',
    'pricing.feature.br.5':   'Delivered in 1 to 2 weeks',
    'pricing.moneymath':       '4 extra bookings per month at CHF 120 each is CHF 480. Pays for itself in under 4 months.',
    'pricing.careplan':        'Care Plan available after launch. CHF 150 to 250 per month. Updates, monitoring, Google checks, missed-call review.',
    'pricing.allprices':       'All prices are starting points. The free audit gives you a clear picture before any commitment.',

    // QuickCheck section
    'quickcheck.eyebrow':    'Booking leak finder',
    'quickcheck.headline':   'Find where your business is losing bookings',
    'quickcheck.body':       'Six common leak points. Check how many apply to your business right now.',
    'quickcheck.card.title': 'Common booking leaks',
    'quickcheck.item.1':     'No website, or only an Instagram or Treatwell profile',
    'quickcheck.item.2':     'Phone number is not tappable on mobile',
    'quickcheck.item.3':     'Google listing has no hours, photos, or fewer than 10 reviews',
    'quickcheck.item.4':     'Site loads slowly or looks broken on a phone screen',
    'quickcheck.item.5':     'Missed calls go unanswered with no automatic follow-up',
    'quickcheck.item.6':     'No online booking. Clients must call or message to book.',
    'quickcheck.cta':        'Book your free audit',
    'quickcheck.microcopy':  'Takes 10 minutes. No commitment.',

    // HowItWorks section
    'how.eyebrow':    'Process',
    'how.headline':   'How it works',
    'how.cta':        'Book your free audit',
    'step.0.title':   'Book a free audit',
    'step.0.desc':    '15-minute call or walk-in. I check your current setup.',
    'step.1.title':   'We find the leaks',
    'step.1.desc':    'Audit of your Google presence, website, and missed-call setup.',
    'step.2.title':   'I build the fix',
    'step.2.desc':    'Website, Google readiness, missed-call system. Live in 1 week.',
    'step.3.title':   'Bookings improve',
    'step.3.desc':    'You get more confirmed clients. I track what changed.',

    // Journey timeline (HowItWorks replacement)
    'journey.1.name': 'Search',
    'journey.1.desc': 'Someone searches for your service nearby.',
    'journey.2.name': 'Google Maps',
    'journey.2.desc': 'Do they find you? Is your profile complete?',
    'journey.3.name': 'Website',
    'journey.3.desc': 'Does it load fast? Are your services clear?',
    'journey.4.name': 'Trust',
    'journey.4.desc': 'Reviews, hours, a tappable phone number.',
    'journey.5.name': 'Contact',
    'journey.5.desc': 'They call. You are with a client. What happens?',
    'journey.6.name': 'Confirmed',
    'journey.6.desc': 'Booking made. No leak.',

    // Final CTA
    'finalcta.headline': 'See what you are losing right now. Takes 10 minutes.',

    // FAQ section
    'faq.eyebrow':   'FAQ',
    'faq.headline':  'Common questions',
    'faq.0.q': 'Is this only for beauty salons?',
    'faq.0.a': 'No. LumaFlow works for any appointment-based local business: salons, physio practices, massage studios, wellness clinics, coaches, and other local service providers.',
    'faq.1.q': 'Do I need a website?',
    'faq.1.a': "If clients search for you and cannot find a fast, mobile-friendly site with your phone number and services, yes. Most local businesses in Zürich still rely on Treatwell, Instagram, or outdated WordPress sites from 2019. None of these perform well in local Google search. A dedicated site changes that.",
    'faq.2.q': 'I already have a website. Why do I need this?',
    'faq.2.a': "Having a website and having a website that recovers bookings are two different things. Most local business websites exist but don't actively help customers understand, trust, and book. The quick check shows the difference.",
    'faq.3.q': 'What if I already use Treatwell or Fresha?',
    'faq.3.a': 'Platforms are great for discovery, but they charge a fee for every booking and own the customer relationship. A direct booking option alongside your platform profile means more profitable bookings over time.',
    'faq.4.q': 'Can you help if I only use Instagram?',
    'faq.4.a': 'Yes. Instagram builds awareness, but customers who find you on Instagram still look for a website to trust you and book. LumaFlow helps build that bridge.',
    'faq.5.q': 'Can you work with my existing booking system?',
    'faq.5.a': 'Yes. LumaFlow works alongside Calendly, Fresha, WhatsApp booking, phone booking, and other tools. The goal is a clearer path to whatever booking method you already use.',
    'faq.6.q': 'Do you help with Google visibility?',
    'faq.6.a': 'Yes. Local search visibility is part of every project. Your content is structured so Google can understand what you offer and show you to the right people nearby.',
    'faq.7.q': 'How long does it take?',
    'faq.7.a': 'Most projects go live within one week of receiving your materials. Photos, services, prices, and opening hours. I work on a tight, predictable schedule. You send me the materials, I build and deploy. No long back-and-forth.',
    'faq.8.q': 'Can we start small?',
    'faq.8.a': 'Yes. The quick check is free and takes a few minutes. From there, you decide what makes sense. There is no minimum commitment to get started.',

    // HeroAudit
    'audit.header':   'Search for your business on Google right now. What do you see?',
    'audit.subhead':  'Takes 10 seconds. No signup needed.',
    'audit.opt.invisible.title': 'Nothing. Or only Instagram or Treatwell.',
    'audit.opt.invisible.sub':   'No own website. Not visible on Google Maps.',
    'audit.opt.broken.title':    'A website, but bad or slow on mobile.',
    'audit.opt.broken.sub':      'No booking button. Phone number not tappable.',
    'audit.opt.treatwell.title': 'A Treatwell or Fresha profile. That is my website.',
    'audit.opt.treatwell.sub':   'I rely on the platform for bookings and visibility.',
    'audit.opt.calls.title':     'Looks fine. But I miss calls when with a client.',
    'audit.opt.calls.sub':       'Site and Google profile work. But calls go unanswered.',
    'audit.invisible.eyebrow':   'Completely invisible online',
    'audit.invisible.diagnosis': 'Anyone searching for your type of business in your area finds your competitors. Not you. Every day this continues is bookings you will never know you lost.',
    'audit.invisible.lossUnit':  'to CHF 1,800 lost per month, estimated',
    'audit.invisible.math':      'A site that ranks locally costs CHF 1,800 once.',
    'audit.invisible.b1':        'You do not appear when someone searches your niche nearby',
    'audit.invisible.b2':        'No tappable phone. No booking path. No trust signals.',
    'audit.invisible.b3':        'Competitors with a basic site are taking your clients right now',
    'audit.broken.eyebrow':      'Visible but not converting',
    'audit.broken.diagnosis':    'People find you. They open your site on their phone. Then they leave. A site that does not work on mobile loses 6 out of 10 visitors before they see your services.',
    'audit.broken.lossUnit':     'to CHF 960 lost per month, estimated',
    'audit.broken.math':         'These are people who already found you. They just could not act fast enough.',
    'audit.broken.b1':           'Site loads too slowly. Visitors leave in under 3 seconds.',
    'audit.broken.b2':           'No booking button or tappable phone above the fold',
    'audit.broken.b3':           'Services and prices hard to find. Visitors give up.',
    'audit.treatwell.eyebrow':   'Platform dependent',
    'audit.treatwell.diagnosis': 'Treatwell and Fresha own your client relationship. If they change their algorithm, raise fees, or a competitor outbids you, your bookings drop. You have no fallback.',
    'audit.treatwell.lossUnit':  'of your revenue goes to platform fees every month',
    'audit.treatwell.math':      'An own site that ranks on Google costs CHF 1,800 once. No fees. No algorithm. No competitor sitting next to your listing.',
    'audit.treatwell.b1':        'You pay per booking to a platform you do not control',
    'audit.treatwell.b2':        'Your profile sits next to 12 competitors. Clients compare on price.',
    'audit.treatwell.b3':        'No direct Google presence. No own client list. No own brand.',
    'audit.calls.eyebrow':       'Leaking at the finish line',
    'audit.calls.diagnosis':     'Your online presence works. But every call that goes unanswered while you are with a client is a booking that calls the next number. Most callers do not leave a voicemail.',
    'audit.calls.lossUnit':      'lost per month from missed calls alone, estimated',
    'audit.calls.math':          'An automated missed-call system costs CHF 600 once and pays for itself in the first week.',
    'audit.calls.b1':            'Missed calls during sessions have no automatic follow-up',
    'audit.calls.b2':            'Callers move on within 2 minutes if nobody responds',
    'audit.calls.b3':            'You lose bookings you will never know about',
    'audit.cta.text':            'Book your free audit',
    'audit.disclaimer':          '10 minutes. No commitment. I show you exactly what to fix.',
    'audit.reset':               'That is not quite right. Go back.',

    // Contact
    'contact.label':            'Free audit',
    'contact.headline':         'Find out exactly where your business loses bookings.',
    'contact.subline':          'Free 10-minute audit. No commitment. I will show you the three things costing you bookings right now.',
    'contact.besiana.name':     'Besiana',
    'contact.besiana.role':     'Based in Zürich. I personally review your booking setup.',
    'contact.besiana.trust':    'Free audit. No commitment. Clear next steps within 24 hours.',
    'contact.trust.1':          'Free. No commitment required.',
    'contact.trust.2':          'Takes 10 minutes of your time.',
    'contact.trust.3':          'No pitch on the first call.',
    'contact.form.title':                'Send audit request',
    'contact.form.name':                 'Name',
    'contact.form.name.optional':        '(optional)',
    'contact.form.name.placeholder':     'Anna Müller',
    'contact.form.phone':                'Phone number',
    'contact.form.business':             'Business type',
    'contact.form.business.placeholder':  'Select your business type',
    'contact.form.option.beauty-nail':    'Beauty or nail salon',
    'contact.form.option.massage':        'Massage studio',
    'contact.form.option.physio':         'Physiotherapy practice',
    'contact.form.option.wellness':       'Wellness provider',
    'contact.form.option.trades':         'Local trades or services',
    'contact.form.option.other':          'Other',
    'contact.form.business.error':        'Please select a business type.',
    'contact.form.other':                'What kind of business?',
    'contact.form.other.placeholder':    'e.g. catering, coaching, repairs',
    'contact.form.other.error':          'Please describe your business type.',
    'contact.form.message':              'Anything else',
    'contact.form.message.placeholder':  "What's your main challenge right now?",
    'contact.form.required':             'Required fields',
    'contact.form.submit':               'Send audit request',
    'contact.form.submitting':           'Sending...',
    'contact.form.disclaimer':           'I reply within 24 hours. No spam.',
    'contact.form.phone.error':          'Phone number is required.',
    'contact.success.title':             'Received.',
    'contact.success.body':              'I will be in touch within 24 hours.',

    // Footer
    'footer.tagline':          'Booking recovery and customer growth for local businesses in Zürich and Switzerland.',
    'footer.contact.label':    'Get in touch',
    'footer.cta':              'Book your free audit',
    'footer.copyright':        'LumaFlow. Zürich, Switzerland.',
    'footer.byline':           'Mobile-first websites, Google visibility, and booking recovery for local businesses.',
    'footer.link.home':        'Home',
    'footer.link.solutions':   'Solutions',
    'footer.link.liveDemo':    'Live demo',
    'footer.link.pricing':     'Pricing',
    'footer.link.faq':         'FAQ',
    'footer.link.contact':     'Contact',
  },

  de: {
    // Nav — Home stays "Home" per spec
    'nav.home':       'Home',
    'nav.solutions':  'Lösungen',
    'nav.liveDemo':   'Demo',
    'nav.pricing':    'Preise',
    'nav.faq':        'FAQ',
    'nav.contact':    'Kontakt',
    'nav.cta':        'Kostenlose Analyse buchen',

    // Hero
    'hero.headline':       'Ihr Angebot stimmt. Der Weg zur Buchung nicht.',
    'hero.subline':        'Die meisten Betriebe verlieren Buchungen still und unbemerkt. Immer an denselben Stellen.',
    'hero.cta.primary':    'Kostenlose Analyse buchen',
    'hero.cta.secondary':  'Live-Demo ansehen',
    'hero.badge.1':        'Zürich-basiert',
    'hero.badge.2':        'Mobile-first',
    'hero.badge.3':        'Website · Google · Buchungen',
    'hero.trust':          'Aus Zürich. Persönlich geprüft. Klare nächste Schritte innerhalb von 24 Stunden.',
    'hero.callout.1':      '',
    'hero.callout.2':      'Die meisten verlorenen Buchungen passieren, bevor jemand anruft.',
    'hero.callout.3':      '',

    // Sticky CTA
    'sticky.cta': 'Kostenlose Analyse buchen',

    // Before/After section
    'before.label':       'Der Unterschied',
    'before.headline.1':  'Kunden springen ab.',
    'before.headline.2':  'Oder sie wissen genau, was sie als Nächstes tun sollen.',
    'before.col.before':  'Vorher',
    'before.col.after':   'Nachher',
    'before.item.1':      'Keine klickbare Telefonnummer auf dem Handy',
    'before.item.2':      'Google-Eintrag unvollständig oder ohne Öffnungszeiten',
    'before.item.3':      'Seite lädt zu langsam. Besucher springt nach 3 Sekunden ab.',
    'before.item.4':      'Verpasster Anruf ohne automatische Rückmeldung',
    'before.item.5':      'Buchung nur per Instagram oder Treatwell',
    'after.item.1':       'Telefonnummer ist direkt anrufbar',
    'after.item.2':       'Google-Profil vollständig, bewertet und indexiert',
    'after.item.3':       'Seite lädt in unter 2 Sekunden über mobile Daten',
    'after.item.4':       'Verpasster Anruf löst eine automatische Rückmeldung aus',
    'after.item.5':       'Kunde kann in unter 10 Sekunden ab der Suche buchen',

    // Problem section
    'problem.eyebrow':         'Das eigentliche Problem',
    'problem.headline.1':      'Das Problem ist nicht Ihr Marketing.',
    'problem.headline.2':      'Es ist Ihr Buchungsweg.',
    'problem.body':            'Die meisten Buchungen gehen verloren, bevor jemand anruft.',
    'problem.0.title':         'Kein klarer nächster Schritt',
    'problem.0.desc':          'Besucher mögen, was sie sehen, wissen aber nicht, was sie als Nächstes tun sollen. Kein Buchungslink, kein klarer Kontaktweg.',
    'problem.1.title':         'Verpasste Anrufe verschwinden',
    'problem.1.desc':          'Sie sind in einer Sitzung. Das Telefon klingelt, Sie verpassen es. Niemand meldet sich zurück. Der Kunde bucht woanders.',
    'problem.2.title':         'Mobilseite erzeugt Reibung',
    'problem.2.desc':          'Die meisten Kunden schauen Sie auf dem Handy an. Wenn die Seite unklar oder langsam ist, gehen sie, bevor sie sich melden.',
    'problem.3.title':         'Vertrauen kommt zu spät',
    'problem.3.desc':          'Bewertungen, Leistungen und Preise müssen früh sichtbar sein. Wenn sie versteckt oder nicht vorhanden sind, zögern Kunden und gehen.',
    'problem.niches.label':    'Für wen es ist',
    'problem.niches.headline': 'Für jedes lokale Geschäft, bei dem Buchungen wichtig sind',
    'problem.niche.0.title':   'Beauty und Wellness',
    'problem.niche.0.desc':    'Massagestudios, Salons, Nagelstudios, Kosmetik',
    'problem.niche.1.title':   'Gesundheit und Medizin',
    'problem.niche.1.desc':    'Physiotherapeuten, Podologen, medizinische Kosmetik',
    'problem.niche.2.title':   'Lokale Dienstleister',
    'problem.niche.2.desc':    'Klempner, Catering-Betriebe, wer vom Telefon lebt',
    'problem.leak.label':      'LÜCKE',

    // Demo section
    'demo.eyebrow':   'LIVE-DEMO',
    'demo.headline':  'So kann eine buchungsbereite Website aussehen',
    'demo.subline':   'Ein echtes Beispiel, das zeigt, wie Leistungen, Vertrauen, mobile Buchung und klare Nutzerführung zusammenwirken.',
    'demo.bullet.1':  'Leistungen und Preise schnell erfassbar',
    'demo.bullet.2':  'Buchung früh sichtbar',
    'demo.bullet.3':  'Mobil optimiert für lokale Kundschaft',
    'demo.note':      'Demo basiert auf Maison Lumière als Beispielgeschäft.',
    'demo.caption':   'Demo-Beispiel: Maison Lumière Beauty Studio, Zürich. Gebaut, um zu zeigen, wie LumaFlow ein lokales Geschäft online buchungsbereit macht.',
    'demo.cta':       'Live-Demo ansehen',

    // Solution section
    'solution.eyebrow':      'WAS ICH LÖSE',
    'solution.headline':     'Ich mache aus einem löchrigen Buchungsweg eine klare Kundenreise.',
    'solution.subline':      'LumaFlow verbindet die Bausteine, die bei vielen lokalen Geschäften getrennt bleiben: Website, Google-Profil, Buchungsweg, Telefonkontakt und Follow-up.',
    'solution.card1.title':  'Klarer Buchungsweg auf dem Handy',
    'solution.card1.copy':   'Kunden sehen Ihre Leistungen, gewinnen Vertrauen und wissen sofort, wie sie buchen können.',
    'solution.card2.title':  'Lokale Präsenz für Google',
    'solution.card2.copy':   'Website und Google-Profil arbeiten zusammen, damit Kunden Sie schneller finden, verstehen und kontaktieren.',
    'solution.card3.title':  'Rückgewinnung verpasster Anrufe',
    'solution.card3.copy':   'Wenn Sie einen Anruf verpassen, erhält der Kunde trotzdem eine schnelle Rückmeldung statt zum nächsten Anbieter zu wechseln.',
    'solution.cta':          'Kostenlose Analyse buchen',

    // Pricing section
    'pricing.eyebrow':              'Pakete',
    'pricing.section.headline':     'Fangen Sie dort an, wo es für Ihr Geschäft Sinn macht',
    'pricing.section.subline':      'Jedes Projekt beginnt mit einer kostenlosen Analyse, damit Sie genau wissen, was sinnvoll ist, bevor Sie sich festlegen.',
    'pricing.badge':                'Am beliebtesten',
    'pricing.from':                 'ab',
    'pricing.cta':                  'Kostenlose Analyse buchen',
    'pricing.tier.localPresence':   'Lokale Präsenz',
    'pricing.tier.bookingWebsite':  'Buchungswebsite',
    'pricing.tier.fullRecovery':    'Komplettes Buchungs-Recovery-System',
    'pricing.tagline.localPresence':  'Für Betriebe, die eine klare, auffindbare Online-Präsenz brauchen.',
    'pricing.tagline.bookingWebsite': 'Für Betriebe, die mehr Besucher in Buchungen verwandeln wollen.',
    'pricing.tagline.fullRecovery':   'Für Betriebe, die Website, Buchungssystem und Follow-up brauchen.',
    'pricing.feature.lp.1':   'Kunden können Sie auf Google finden',
    'pricing.feature.lp.2':   'Ihre Telefonnummer funktioniert auf dem Handy',
    'pricing.feature.lp.3':   'Google Business Profile vollständig und indexiert',
    'pricing.feature.lp.4':   'Fertig in 1 Woche',
    'pricing.feature.bw.1':   'Kunden können in unter 10 Sekunden ab der Suche buchen',
    'pricing.feature.bw.2':   'Klickbare Telefonnummer, Buchungsformular, Google Maps',
    'pricing.feature.bw.3':   'FAQ-Bereich, der Anfragen vor der Buchung reduziert',
    'pricing.feature.bw.4':   'Lokale SEO-Struktur integriert',
    'pricing.feature.bw.5':   'Fertig in 1 Woche',
    'pricing.feature.br.1':   'Alles aus der Buchungswebsite',
    'pricing.feature.br.2':   'Automatische Rückmeldung bei verpassten Anrufen',
    'pricing.feature.br.3':   'Google Business Profile optimiert',
    'pricing.feature.br.4':   'Prozess für Bewertungsanfragen',
    'pricing.feature.br.5':   'Fertig in 1 bis 2 Wochen',
    'pricing.moneymath':       '4 extra Buchungen pro Monat à CHF 120 sind CHF 480. Amortisiert sich in unter 4 Monaten.',
    'pricing.careplan':        'Care-Plan verfügbar nach dem Launch. CHF 150 bis 250 pro Monat. Updates, Monitoring, Google-Checks, Anruf-Auswertung.',
    'pricing.allprices':       'Alle Preise sind Ausgangspunkte. Die kostenlose Analyse gibt Ihnen ein klares Bild, bevor Sie sich festlegen.',

    // QuickCheck section
    'quickcheck.eyebrow':    'Buchungslücken-Check',
    'quickcheck.headline':   'Finden Sie, wo Ihr Betrieb Buchungen verliert',
    'quickcheck.body':       'Sechs häufige Verlustpunkte. Prüfen Sie, wie viele auf Ihr Geschäft zutreffen.',
    'quickcheck.card.title': 'Häufige Buchungslücken',
    'quickcheck.item.1':     'Keine Website, nur Instagram oder Treatwell',
    'quickcheck.item.2':     'Telefonnummer auf dem Handy nicht direkt anrufbar',
    'quickcheck.item.3':     'Google-Eintrag ohne Öffnungszeiten, Fotos oder weniger als 10 Bewertungen',
    'quickcheck.item.4':     'Seite lädt langsam oder sieht auf dem Handy fehlerhaft aus',
    'quickcheck.item.5':     'Verpasste Anrufe ohne automatische Rückmeldung',
    'quickcheck.item.6':     'Keine Online-Buchung. Kunden müssen anrufen oder schreiben.',
    'quickcheck.cta':        'Kostenlose Analyse buchen',
    'quickcheck.microcopy':  'Dauert 10 Minuten. Keine Verpflichtung.',

    // HowItWorks section
    'how.eyebrow':    'Ablauf',
    'how.headline':   'So funktioniert es',
    'how.cta':        'Kostenlose Analyse buchen',
    'step.0.title':   'Kostenlose Analyse anfragen',
    'step.0.desc':    '15-Minuten-Gespräch. Ich prüfe Ihre aktuelle Situation.',
    'step.1.title':   'Wir finden die Lücken',
    'step.1.desc':    'Analyse Ihres Google-Auftritts, der Website und des Anruf-Setups.',
    'step.2.title':   'Ich setze es um',
    'step.2.desc':    'Website, Google-Auftritt, Anruf-System. Live in 1 Woche.',
    'step.3.title':   'Buchungen steigen',
    'step.3.desc':    'Sie erhalten mehr bestätigte Kunden. Ich verfolge, was sich verändert hat.',

    // Journey timeline (HowItWorks replacement)
    'journey.1.name': 'Suche',
    'journey.1.desc': 'Jemand sucht nach Ihrer Leistung in Ihrer Nähe.',
    'journey.2.name': 'Google Maps',
    'journey.2.desc': 'Finden sie Sie? Ist Ihr Profil vollständig?',
    'journey.3.name': 'Website',
    'journey.3.desc': 'Lädt die Seite schnell? Sind die Leistungen klar?',
    'journey.4.name': 'Vertrauen',
    'journey.4.desc': 'Bewertungen, Öffnungszeiten, direkt anrufbare Nummer.',
    'journey.5.name': 'Kontakt',
    'journey.5.desc': 'Rufen sie an und Sie sind besetzt. Was passiert dann?',
    'journey.6.name': 'Gebucht',
    'journey.6.desc': 'Buchung bestätigt. Kein Verlust.',

    // Final CTA
    'finalcta.headline': 'Sehen Sie in 10 Minuten, was Sie gerade verlieren.',

    // FAQ section
    'faq.eyebrow':   'FAQ',
    'faq.headline':  'Häufige Fragen',
    'faq.0.q': 'Ist das nur für Schönheitssalons?',
    'faq.0.a': 'Nein. LumaFlow funktioniert für jedes terminbasierte lokale Geschäft: Salons, Physiotherapien, Massagestudios, Wellness-Angebote, Coaches und andere lokale Dienstleister.',
    'faq.1.q': 'Brauche ich überhaupt eine Website?',
    'faq.1.a': 'Wenn Kunden nach Ihnen suchen und keine schnelle, mobilfreundliche Seite mit Telefonnummer und Leistungen finden, ja. Die meisten lokalen Betriebe in Zürich setzen noch auf Treatwell, Instagram oder veraltete WordPress-Seiten. Keine davon funktioniert gut in der lokalen Google-Suche. Eine eigene Seite ändert das.',
    'faq.2.q': 'Ich habe schon eine Website. Warum brauche ich das?',
    'faq.2.a': 'Eine Website zu haben und eine Website zu haben, die Buchungen zurückgewinnt, sind zwei verschiedene Dinge. Die meisten lokalen Geschäftswebsites existieren, helfen Kunden aber nicht aktiv dabei, zu verstehen, zu vertrauen und zu buchen. Der Kurzcheck zeigt den Unterschied.',
    'faq.3.q': 'Was, wenn ich bereits Treatwell oder Fresha nutze?',
    'faq.3.a': 'Plattformen sind gut für die Sichtbarkeit, berechnen aber für jede Buchung eine Gebühr und besitzen die Kundenbeziehung. Eine direkte Buchungsoption neben Ihrem Plattformprofil bedeutet profitablere Buchungen auf Dauer.',
    'faq.4.q': 'Können Sie mir helfen, wenn ich nur Instagram nutze?',
    'faq.4.a': 'Ja. Instagram schafft Aufmerksamkeit, aber Kunden, die Sie auf Instagram finden, suchen trotzdem nach einer Website, um Ihnen zu vertrauen und zu buchen. LumaFlow hilft, diese Brücke zu bauen.',
    'faq.5.q': 'Können Sie mit meinem bestehenden Buchungssystem arbeiten?',
    'faq.5.a': 'Ja. LumaFlow funktioniert zusammen mit Calendly, Fresha, WhatsApp-Buchung, Telefonbuchung und anderen Systemen. Das Ziel ist ein klarerer Weg zu Ihrer bestehenden Buchungsmethode.',
    'faq.6.q': 'Helfen Sie bei der Google-Sichtbarkeit?',
    'faq.6.a': 'Ja. Lokale Suchsichtbarkeit ist Teil jedes Projekts. Ihre Inhalte werden so strukturiert, dass Google versteht, was Sie anbieten, und Sie den richtigen Menschen in der Nähe zeigt.',
    'faq.7.q': 'Wie lange dauert es?',
    'faq.7.a': 'Die meisten Projekte gehen innerhalb einer Woche nach Eingang Ihrer Materialien live. Fotos, Leistungen, Preise und Öffnungszeiten. Ich arbeite nach einem straffen, planbaren Ablauf. Sie schicken mir die Materialien, ich baue und veröffentliche. Kein langes Hin und Her.',
    'faq.8.q': 'Können wir klein anfangen?',
    'faq.8.a': 'Ja. Der Kurzcheck ist kostenlos und dauert ein paar Minuten. Von dort entscheiden Sie, was sinnvoll ist. Es gibt keine Mindestverpflichtung, um anzufangen.',

    // HeroAudit
    'audit.header':   'Suchen Sie Ihr Geschäft jetzt gerade auf Google. Was sehen Sie?',
    'audit.subhead':  'Dauert 10 Sekunden. Keine Anmeldung nötig.',
    'audit.opt.invisible.title': 'Nichts. Oder nur Instagram oder Treatwell.',
    'audit.opt.invisible.sub':   'Keine eigene Website. Nicht auf Google Maps sichtbar.',
    'audit.opt.broken.title':    'Eine Website, aber schlecht oder langsam auf dem Handy.',
    'audit.opt.broken.sub':      'Kein Buchungsbutton. Telefonnummer nicht direkt anrufbar.',
    'audit.opt.treatwell.title': 'Ein Treatwell- oder Fresha-Profil. Das ist meine Website.',
    'audit.opt.treatwell.sub':   'Ich verlasse mich für Buchungen und Sichtbarkeit auf die Plattform.',
    'audit.opt.calls.title':     'Sieht gut aus. Aber ich verpasse Anrufe während Sitzungen.',
    'audit.opt.calls.sub':       'Seite und Google-Profil funktionieren. Aber Anrufe bleiben unbeantwortet.',
    'audit.invisible.eyebrow':   'Online komplett unsichtbar',
    'audit.invisible.diagnosis': 'Wer in Ihrer Gegend nach Ihrem Angebot sucht, findet Ihre Mitbewerber. Nicht Sie. Jeder Tag so kostet Sie Buchungen, von denen Sie nie erfahren.',
    'audit.invisible.lossUnit':  'bis CHF 1.800 Verlust pro Monat, geschätzt',
    'audit.invisible.math':      'Eine Seite, die lokal rankt, kostet CHF 1.800 einmalig.',
    'audit.invisible.b1':        'Sie erscheinen nicht, wenn jemand in Ihrer Nähe nach Ihrem Angebot sucht',
    'audit.invisible.b2':        'Keine anrufbare Nummer. Kein Buchungsweg. Keine Vertrauenssignale.',
    'audit.invisible.b3':        'Mitbewerber mit einer einfachen Seite nehmen Ihnen gerade Kunden weg',
    'audit.broken.eyebrow':      'Sichtbar, aber konvertiert nicht',
    'audit.broken.diagnosis':    'Leute finden Sie. Sie öffnen Ihre Seite auf dem Handy. Dann gehen sie. Eine Seite, die auf dem Handy nicht funktioniert, verliert 6 von 10 Besuchern, bevor sie Ihre Leistungen sehen.',
    'audit.broken.lossUnit':     'bis CHF 960 Verlust pro Monat, geschätzt',
    'audit.broken.math':         'Das sind Menschen, die Sie bereits gefunden haben. Sie konnten nur nicht schnell genug handeln.',
    'audit.broken.b1':           'Seite lädt zu langsam. Besucher gehen in unter 3 Sekunden.',
    'audit.broken.b2':           'Kein Buchungsbutton oder anrufbare Nummer im sichtbaren Bereich',
    'audit.broken.b3':           'Leistungen und Preise schwer zu finden. Besucher geben auf.',
    'audit.treatwell.eyebrow':   'Plattformabhängig',
    'audit.treatwell.diagnosis': 'Treatwell und Fresha besitzen Ihre Kundenbeziehung. Wenn sie ihren Algorithmus ändern, Gebühren erhöhen oder ein Mitbewerber Sie überbietet, brechen Ihre Buchungen ein. Sie haben keinen Ausweg.',
    'audit.treatwell.lossUnit':  'Ihres Umsatzes fliessen jeden Monat als Plattformgebühren ab',
    'audit.treatwell.math':      'Eine eigene Seite, die bei Google rankt, kostet CHF 1.800 einmalig. Keine Gebühren. Kein Algorithmus. Kein Mitbewerber direkt neben Ihrem Eintrag.',
    'audit.treatwell.b1':        'Sie zahlen pro Buchung an eine Plattform, die Sie nicht kontrollieren',
    'audit.treatwell.b2':        'Ihr Profil steht neben 12 Mitbewerbern. Kunden vergleichen über den Preis.',
    'audit.treatwell.b3':        'Keine direkte Google-Präsenz. Keine eigene Kundenliste. Keine eigene Marke.',
    'audit.calls.eyebrow':       'Verlust kurz vor dem Ziel',
    'audit.calls.diagnosis':     'Ihre Online-Präsenz funktioniert. Aber jeder unbeantwortete Anruf während einer Sitzung ist eine Buchung, die die nächste Nummer anruft. Die meisten Anrufer hinterlassen keine Nachricht.',
    'audit.calls.lossUnit':      'Verlust pro Monat allein durch verpasste Anrufe, geschätzt',
    'audit.calls.math':          'Ein automatisches Anruf-System kostet CHF 600 einmalig und amortisiert sich in der ersten Woche.',
    'audit.calls.b1':            'Verpasste Anrufe während Sitzungen haben keine automatische Nachricht',
    'audit.calls.b2':            'Anrufer gehen weiter, wenn innerhalb von 2 Minuten niemand antwortet',
    'audit.calls.b3':            'Sie verlieren Buchungen, von denen Sie nie erfahren',
    'audit.cta.text':            'Kostenlose Analyse buchen',
    'audit.disclaimer':          '10 Minuten. Keine Verpflichtung. Ich zeige Ihnen genau, was zu beheben ist.',
    'audit.reset':               'Das trifft nicht ganz zu. Zurück.',

    // Contact
    'contact.label':            'Kostenlose Analyse',
    'contact.headline':         'Finden Sie heraus, wo Ihr Geschäft Buchungen verliert.',
    'contact.subline':          'Kostenlose 10-Minuten-Analyse. Keine Verpflichtung. Ich zeige Ihnen die drei Dinge, die Ihnen jetzt Buchungen kosten.',
    'contact.besiana.name':     'Besiana',
    'contact.besiana.role':     'Aus Zürich. Ich prüfe Ihren Buchungsweg persönlich.',
    'contact.besiana.trust':    'Kostenlose Analyse. Keine Verpflichtung. Klare nächste Schritte innerhalb von 24 Stunden.',
    'contact.trust.1':          'Kostenlos. Keine Verpflichtung.',
    'contact.trust.2':          'Dauert nur 10 Minuten.',
    'contact.trust.3':          'Kein Verkaufsgespräch beim ersten Kontakt.',
    'contact.form.title':                'Kostenlose Analyse buchen',
    'contact.form.name':                 'Name',
    'contact.form.name.optional':        '(optional)',
    'contact.form.name.placeholder':     'Anna Müller',
    'contact.form.phone':                'Telefonnummer',
    'contact.form.business':             'Geschäftstyp',
    'contact.form.business.placeholder':  'Geschäftstyp auswählen',
    'contact.form.option.beauty-nail':    'Beauty- oder Nagelstudio',
    'contact.form.option.massage':        'Massagestudio',
    'contact.form.option.physio':         'Physiotherapiepraxis',
    'contact.form.option.wellness':       'Wellness-Anbieter',
    'contact.form.option.trades':         'Lokale Handwerker oder Dienstleister',
    'contact.form.option.other':          'Anderes',
    'contact.form.business.error':        'Bitte wählen Sie einen Geschäftstyp aus.',
    'contact.form.other':                'Welche Art von Geschäft?',
    'contact.form.other.placeholder':    'z.B. Catering, Coaching, Reparaturen',
    'contact.form.other.error':          'Bitte beschreiben Sie Ihren Geschäftstyp.',
    'contact.form.message':              'Sonstiges',
    'contact.form.message.placeholder':  'Was ist Ihre grösste Herausforderung?',
    'contact.form.required':             'Pflichtfelder',
    'contact.form.submit':               'Analyse senden',
    'contact.form.submitting':           'Wird gesendet...',
    'contact.form.disclaimer':           'Ich melde mich innerhalb von 24 Stunden. Kein Spam.',
    'contact.form.phone.error':          'Telefonnummer ist erforderlich.',
    'contact.success.title':             'Erhalten.',
    'contact.success.body':              'Ich melde mich innerhalb von 24 Stunden.',

    // Footer — Home stays "Home" per spec
    'footer.tagline':          'Buchungsoptimierung und Kundengewinnung für lokale Geschäfte in Zürich und der Schweiz.',
    'footer.contact.label':    'Kontakt',
    'footer.cta':              'Kostenlose Analyse buchen',
    'footer.copyright':        'LumaFlow. Zürich, Schweiz.',
    'footer.byline':           'Mobile-first Websites, Google-Sichtbarkeit und Buchungsoptimierung für lokale Geschäfte.',
    'footer.link.home':        'Home',
    'footer.link.solutions':   'Lösungen',
    'footer.link.liveDemo':    'Live-Demo',
    'footer.link.pricing':     'Preise',
    'footer.link.faq':         'FAQ',
    'footer.link.contact':     'Kontakt',
  },
};

const LanguageContext = createContext<LanguageContextValue>({
  lang: 'en',
  setLang: () => {},
  t: (key) => key,
});

const metaByLang: Record<Lang, { title: string; description: string }> = {
  en: {
    title: 'LumaFlow | Stop Losing Bookings Before They Happen',
    description: 'LumaFlow helps local businesses in Zürich recover missed bookings with a fast mobile website, better Google visibility, and automated missed-call follow-up. Free audit.',
  },
  de: {
    title: 'LumaFlow | Buchungen werden gerade verloren. Finden Sie heraus wo.',
    description: 'LumaFlow hilft lokalen Betrieben in Zürich, verlorene Buchungen zurückzugewinnen. Schnelle mobile Website, bessere Google-Sichtbarkeit, automatisches Anruf-Follow-up. Kostenlose Analyse.',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('en');

  useEffect(() => {
    const { title, description } = metaByLang[lang];
    document.title = title;
    const metaDesc = document.querySelector('meta[name="description"]');
    if (metaDesc) metaDesc.setAttribute('content', description);
  }, [lang]);

  const t = (key: string): string =>
    translations[lang][key] ?? translations.en[key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
